[project]
name = "automacao-plugins"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "typer",
    "rich",
    "lxml",
]

[dependency-groups]
dev = [
    "pre-commit",
    "pytest",
]

lint = [
    "ruff>=0.11.6"
]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["E402"]

[tool.pytest.ini_options]
addopts = "--verbose"
testpaths = ["tests"]
python_files = ["test_*.py"]
pythonpath = ["src"]

[tool.uv]
package = false
