name: Feature
description: Adiciona nova funcionalidade ao projeto
title: "[FEAT]"
labels: ["To Dev", "V1"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: Descreva a nova feture
      placeholder: Descreva aqui
    validations:
      required: true